### ISSUE TITLE
label displaying in chrome

### ISSUE THREAD

**Issue by despi8** [willsoto/angular-chartist.js#172] opened 2018-02-01 09:40 UTC
I have created a line chart using chartist.js but the labels are not shown and displayed correctly, please do help... If anyone does know how to make it visible... or how we are able to display it....var jbChartCtrl = this;

		    jbChartCtrl.data = {
                labels:[1,2,3],
		        series:[
		            [0,1,3,12,28,30],
		            [],[],[],[],
		            [0,4,4,15,25,30]
		        ]
		    };

		    jbChartCtrl.options = {
		        low: 0,
		        fullWidth: true,
		        showArea: true,
		        axisX: { offset: 60 },
                axisY: { offset: 60 },
		        chartPadding: {
		            right:40
		        }
		    };

		    var chart = new Chartist.Line('.ct-chart', data, options);
look this is how my code is but its not working.....

![image](https://user-images.githubusercontent.com/35991459/35671754-61899e58-070a-11e8-8d74-acfd90d29b9a.png)

**Comment by willsoto** [comment] 2018-02-20 12:38
Duplicate of #171

**Closed by willsoto** 2018-02-20 12:38 UTC
